### ISSUE TITLE
DynamoDb - batch_get_item

### ISSUE THREAD

**Issue by ngr** [bimpression/sosw#109]
Implement this method in DynamoDbClient.
Should use the method of boto3 and preserve it's logic.

**Comment by DrugBug** [comment]
On the way... Fix the batch_get_items_one_table() method.
It's logic is completely broken!

While handling exponential backoff you overwrite db_response without extracting items. DANGER!

Bonus. Implement `max_items` parameter for this function in order to:
- break pagination when reached the limit 
- return just the limited number of items.

//ngr + gil

**Comment by nimirium** [comment]
batch_get_items_one_table fix (and more stuff):
https://github.com/bimpression/sosw/pull/114

**Comment by ngr** [comment]
This is OK since 0.7.13
